### ISSUE TITLE
faster pandas with ray

### ISSUE THREAD

**Issue by andrewvaliente** [bshaw19/Crypto_Trader#3]
import ray.dataframe as pd
https://news.ycombinator.com/item?id=16510610

**Comment by bshaw2019** [comment]
I tried implementing this and unfortunately there is a lot of functions from pandas that haven't been created for Ray including "read_sql" which is one of the main functions we need in table construction since we're using a DB. Maybe we can find another way to implement parallel processing in the meantime, and hopefully ray will add this feature soon.

**Comment by and-rewsmith** [comment]
Why not use the parallel parts from ray and substitute whatever doesn't work with the original pandas functionality?

**Comment by bshaw2019** [comment]
In my opinion we’re better off just multithreading as needed for all functions.
